"""add outcome_summary to steps

Revision ID: 9156c80a53ec
Revises: 9d3996724e5e
Create Date: 2026-07-31 20:58:35.948392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9156c80a53ec'
down_revision: Union[str, None] = '9d3996724e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('outcome_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'outcome_summary')
    # ### end Alembic commands ###
